name: Publish NuGet 2
author: Rebel028
description: Temporary fork of https://github.com/brandedoutcast/publish-nuget/

inputs:
    PROJECT_FILE_PATH:
        description: Filepath of the project to be packaged, relative to root of repository
        required: true
    PACKAGE_NAME:
        description: NuGet package id, used for version detection & defaults to project name
        required: false
    VERSION_FILE_PATH:
        description: Filepath with version info, relative to root of repository & defaults to PROJECT_FILE_PATH
        required: false
    VERSION_REGEX:
        description: Regex pattern to extract version info in a capturing group
        required: false
        default: ^\s*<Version>(.*)<\/Version>\s*$
    VERSION_STATIC:
        description: Useful with external providers like Nerdbank.GitVersioning, ignores VERSION_FILE_PATH & VERSION_REGEX
        required: false
    TAG_COMMIT:
        description: Flag to toggle git tagging, enabled by default
        required: false
        default: true
    TAG_FORMAT:
        description: Format of the git tag, [*] gets replaced with actual version
        required: false
        default: v*
    GITHUB_USER:
        description: Required for packages pushed to Github Package Registry. User allowed to push to repository, defaults to GITHUB_ACTOR (user that triggered the action) 
        required: false
    NUGET_KEY:
        description: API key to authenticate with NuGet server, or a token, issued for GITHUB_USER if you use GPR
        required: false
    NUGET_SOURCE:
        description: NuGet server uri hosting the packages, defaults to https://api.nuget.org
        required: false
        default: https://api.nuget.org
    INCLUDE_SYMBOLS:
        description: Flag to toggle pushing symbols along with nuget package to the server, disabled by default
        required: false
        default: false
    THOW_ERROR_IF_VERSION_EXISTS:
        description: Flag to throw an error when trying to publish an existing version of a package
        required: false
        default: false

outputs:
    VERSION:
        description: Version of the associated git tag

    PACKAGE_NAME:
        description: Name of the NuGet package generated
    
    PACKAGE_PATH:
        description: Path to the generated NuGet package

    SYMBOLS_PACKAGE_NAME:
        description: Name of the symbols package generated
    
    SYMBOLS_PACKAGE_PATH:
        description: Path to the generated symbols package

runs:
    using: node12
    main: index.js

branding:
    icon: package
    color: blue
