name: Publish NuGet
author: Rohith Reddy (@rohith)
description: Build, Pack & Publish a NuGet package with dotnet core on project version change

inputs:
    PROJECT_FILE_PATH:
        description: Filepath of the project to be packaged, relative to root of repository
        required: true
    PACKAGE_NAME:
        description: NuGet package id, used for version detection & defaults to project name
        required: false
    VERSION_FILE_PATH:
        description: Filepath with version info, relative to root of repository & defaults to PROJECT_FILE_PATH
        required: false
    VERSION_REGEX:
        description: Regex pattern to extract version info in a capturing group
        required: false
        default: ^\s*<Version>(.*)<\/Version>\s*$
    VERSION_STATIC:
        description: Useful with external providers like Nerdbank.GitVersioning, ignores VERSION_FILE_PATH & VERSION_REGEX
        required: false
    TAG_COMMIT:
        description: Flag to toggle git tagging, enabled by default
        required: false
        default: true
    TAG_FORMAT:
        description: Format of the git tag, [*] gets replaced with actual version
        required: false
        default: v*
    NUGET_KEY:
        description: API key to authenticate with NuGet server
        required: false
    NUGET_SOURCE:
        description: NuGet server uri hosting the packages, defaults to https://api.nuget.org
        required: false
        default: https://api.nuget.org

outputs:
    VERSION:
        description: Version of the associated git tag

    PACKAGE_NAME:
        description: Name of the NuGet package generated
    
    PACKAGE_PATH:
        description: Path to the generated NuGet package

    SYMBOLS_PACKAGE_NAME:
        description: Name of the symbols package generated
    
    SYMBOLS_PACKAGE_PATH:
        description: Path to the generated symbols package

runs:
    using: node12
    main: index.js

branding:
    icon: package
    color: blue
