name: Publish NuGet
author: Rohith Reddy (@rohith)
description: Build, Pack & Publish NuGet packages with dotnet (.net) core on project version change

inputs:
    PROJECT_FILE_PATH:
        description: Filepath of the project to be packaged, relative to root of repository
        required: true
    VERSION_FILE_PATH:
        description: Filepath containing version info, relative to root of repository. Defaults to `PROJECT_FILE_PATH` if not specified
        required: false
    VERSION_REGEX:
        description: Regex (with version in a capturing group) to extract the version from `VERSION_FILE_PATH`
        required: false
        default: <Version>(.*)<\/Version>
    VERSION_STATIC:
        description: Bypasses version resolution; useful for external providers like Nerdbank.GitVersioning
        required: false
    TAG_COMMIT:
        description: Whether to create a tag when there's a version change
        required: false
        default: true
    TAG_FORMAT:
        description: Format of the tag, `*` is the placeholder for actual version
        required: false
        default: v*
    NUGET_KEY:
        description: API key for the NuGet feed
        required: false
    PACKAGE_NAME:
        description: NuGet package name, required when it's different from the project name
        required: false

runs:
    using: node12
    main: index.js

branding:
    icon: package
    color: blue
